/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_window2 (void);
GtkWidget* create_ghost_window (void);
GtkWidget* create_warning_window (void);
GtkWidget* create_error_window (void);
