/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox1;
  GtkWidget *main_menubar;
  GtkWidget *file_menuitem;
  GtkWidget *file_menuitem_menu;
  GtkWidget *new_menuitem;
  GtkWidget *open_menuitem;
  GtkWidget *save_menuitem;
  GtkWidget *save_as;
  GtkWidget *separator1_menuitem;
  GtkWidget *export_menuitem;
  GtkWidget *separator1;
  GtkWidget *quit_menuitem;
  GtkWidget *edit_menuitem;
  GtkWidget *edit_menuitem_menu;
  GtkWidget *cut_menuitem;
  GtkWidget *copy_menuitem;
  GtkWidget *paste_menuitem;
  GtkWidget *delete_menuitem;
  GtkWidget *view_menuitem;
  GtkWidget *help_menuitem;
  GtkWidget *help_menuitem_menu;
  GtkWidget *about_menuitem;
  GtkWidget *main_toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *new_toolbutton;
  GtkWidget *open_toolbutton;
  GtkWidget *save_toolbutton;
  GtkWidget *n1_separatortoolitem;
  GtkWidget *undo_toolbutton;
  GtkWidget *record_toolbutton;
  GtkWidget *separatortoolitem3;
  GtkWidget *tmp_image;
  GtkWidget *settings_toolbutton;
  GtkWidget *quit_toolbutton;
  GtkWidget *n3_separatortoolitem;
  GSList *select_mode_radiotoolbutton_group = NULL;
  GtkWidget *select_mode_radiotoolbutton;
  GtkWidget *move_mode_radiotoolbutton;
  GtkWidget *signals_mode_radiotoolbutton;
  GtkWidget *rotate_mode_radiotoolbutton;
  GtkWidget *createPoints_mode_radiotoolbutton;
  GtkWidget *createPointFeatures_mode_radiotoolbutton;
  GtkWidget *createLines_mode_radiotoolbutton;
  GtkWidget *connectPoints_mode_radiotoolbutton;
  GtkWidget *createRailLines_mode_radiotoolbutton;
  GtkWidget *createMiscLines_mode_radiotoolbutton;
  GtkWidget *createTracks_mode_radiotoolbutton;
  GtkWidget *import_mode_radiotoolbutton;
  GtkWidget *createFence_mode_radiotoolbutton;
  GtkWidget *catenary_mode_radiotoolbutton;
  GtkWidget *fill_mode_radiotoolbutton;
  GtkWidget *main_hpaned;
  GtkWidget *viewport1;
  GtkWidget *main_drawingarea;
  GtkWidget *properties_scrolledwindow;
  GtkWidget *properties_viewport;
  GtkWidget *properties_vbox;
  GtkWidget *label6;
  GtkWidget *status_hbox;
  GtkWidget *n0_statusbar;
  GtkWidget *n1_statusbar;
  GtkWidget *n2_statusbar;
  GtkWidget *n3_statusbar;
  GtkWidget *n4_statusbar;
  GtkWidget *n5_statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main_window), _("Editor"));

  vbox1 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 1);

  main_menubar = gtk_menu_bar_new ();
  gtk_widget_show (main_menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), main_menubar, FALSE, FALSE, 0);

  file_menuitem = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (file_menuitem);
  gtk_container_add (GTK_CONTAINER (main_menubar), file_menuitem);

  file_menuitem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file_menuitem), file_menuitem_menu);

  new_menuitem = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), new_menuitem);

  open_menuitem = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), open_menuitem);

  save_menuitem = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), save_menuitem);

  save_as = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), save_as);

  separator1_menuitem = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), separator1_menuitem);
  gtk_widget_set_sensitive (separator1_menuitem, FALSE);

  export_menuitem = gtk_menu_item_new_with_mnemonic (_("Export"));
  gtk_widget_show (export_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), export_menuitem);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  quit_menuitem = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit_menuitem);
  gtk_container_add (GTK_CONTAINER (file_menuitem_menu), quit_menuitem);

  edit_menuitem = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (edit_menuitem);
  gtk_container_add (GTK_CONTAINER (main_menubar), edit_menuitem);

  edit_menuitem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit_menuitem), edit_menuitem_menu);

  cut_menuitem = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut_menuitem);
  gtk_container_add (GTK_CONTAINER (edit_menuitem_menu), cut_menuitem);

  copy_menuitem = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy_menuitem);
  gtk_container_add (GTK_CONTAINER (edit_menuitem_menu), copy_menuitem);

  paste_menuitem = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste_menuitem);
  gtk_container_add (GTK_CONTAINER (edit_menuitem_menu), paste_menuitem);

  delete_menuitem = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete_menuitem);
  gtk_container_add (GTK_CONTAINER (edit_menuitem_menu), delete_menuitem);

  view_menuitem = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (view_menuitem);
  gtk_container_add (GTK_CONTAINER (main_menubar), view_menuitem);

  help_menuitem = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (help_menuitem);
  gtk_container_add (GTK_CONTAINER (main_menubar), help_menuitem);

  help_menuitem_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help_menuitem), help_menuitem_menu);

  about_menuitem = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about_menuitem);
  gtk_container_add (GTK_CONTAINER (help_menuitem_menu), about_menuitem);

  main_toolbar = gtk_toolbar_new ();
  gtk_widget_show (main_toolbar);
  gtk_box_pack_start (GTK_BOX (vbox1), main_toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (main_toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (main_toolbar));

  new_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-new");
  gtk_widget_show (new_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), new_toolbutton);

  open_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-open");
  gtk_widget_show (open_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), open_toolbutton);

  save_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-save");
  gtk_widget_show (save_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), save_toolbutton);

  n1_separatortoolitem = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (n1_separatortoolitem);
  gtk_container_add (GTK_CONTAINER (main_toolbar), n1_separatortoolitem);

  undo_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-undo");
  gtk_widget_show (undo_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), undo_toolbutton);
  gtk_widget_set_sensitive (undo_toolbutton, FALSE);

  record_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-media-record");
  gtk_widget_show (record_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), record_toolbutton);
  gtk_widget_set_sensitive (record_toolbutton, FALSE);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (record_toolbutton), tooltips, _("Store current version for 'undo'"), NULL);

  separatortoolitem3 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem3);
  gtk_container_add (GTK_CONTAINER (main_toolbar), separatortoolitem3);

  tmp_image = gtk_image_new_from_stock ("gtk-preferences", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  settings_toolbutton = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Settings"));
  gtk_widget_show (settings_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), settings_toolbutton);

  quit_toolbutton = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_show (quit_toolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), quit_toolbutton);

  n3_separatortoolitem = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (n3_separatortoolitem);
  gtk_container_add (GTK_CONTAINER (main_toolbar), n3_separatortoolitem);

  select_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (select_mode_radiotoolbutton), _("Select"));
  gtk_widget_show (select_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), select_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (select_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (select_mode_radiotoolbutton));
  gtk_toggle_tool_button_set_active (GTK_TOGGLE_TOOL_BUTTON (select_mode_radiotoolbutton), TRUE);

  move_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (move_mode_radiotoolbutton), _("Move"));
  gtk_widget_show (move_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), move_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (move_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (move_mode_radiotoolbutton));

  signals_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (signals_mode_radiotoolbutton), _("Signals"));
  gtk_widget_show (signals_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), signals_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (signals_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (signals_mode_radiotoolbutton));

  rotate_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (rotate_mode_radiotoolbutton), _("Rotate"));
  gtk_container_add (GTK_CONTAINER (main_toolbar), rotate_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (rotate_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (rotate_mode_radiotoolbutton));

  createPoints_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createPoints_mode_radiotoolbutton), _("Points"));
  gtk_widget_show (createPoints_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createPoints_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createPoints_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createPoints_mode_radiotoolbutton));

  createPointFeatures_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createPointFeatures_mode_radiotoolbutton), _("P. feats"));
  gtk_widget_show (createPointFeatures_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createPointFeatures_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createPointFeatures_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createPointFeatures_mode_radiotoolbutton));

  createLines_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createLines_mode_radiotoolbutton), _("Lines"));
  gtk_widget_show (createLines_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createLines_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createLines_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createLines_mode_radiotoolbutton));

  connectPoints_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (connectPoints_mode_radiotoolbutton), _("Connect"));
  gtk_widget_show (connectPoints_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), connectPoints_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (connectPoints_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (connectPoints_mode_radiotoolbutton));

  createRailLines_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createRailLines_mode_radiotoolbutton), _("R. lines"));
  gtk_widget_show (createRailLines_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createRailLines_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createRailLines_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createRailLines_mode_radiotoolbutton));

  createMiscLines_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createMiscLines_mode_radiotoolbutton), _("M. lines"));
  gtk_widget_show (createMiscLines_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createMiscLines_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createMiscLines_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createMiscLines_mode_radiotoolbutton));

  createTracks_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createTracks_mode_radiotoolbutton), _("Tracks"));
  gtk_widget_show (createTracks_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createTracks_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createTracks_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createTracks_mode_radiotoolbutton));

  import_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (import_mode_radiotoolbutton), _("Import"));
  gtk_widget_show (import_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), import_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (import_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (import_mode_radiotoolbutton));

  createFence_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (createFence_mode_radiotoolbutton), _("Fence"));
  gtk_widget_show (createFence_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), createFence_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (createFence_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (createFence_mode_radiotoolbutton));

  catenary_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (catenary_mode_radiotoolbutton), _("Catenary"));
  gtk_widget_show (catenary_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), catenary_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (catenary_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (catenary_mode_radiotoolbutton));

  fill_mode_radiotoolbutton = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (fill_mode_radiotoolbutton), _("Fill"));
  gtk_widget_show (fill_mode_radiotoolbutton);
  gtk_container_add (GTK_CONTAINER (main_toolbar), fill_mode_radiotoolbutton);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (fill_mode_radiotoolbutton), select_mode_radiotoolbutton_group);
  select_mode_radiotoolbutton_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (fill_mode_radiotoolbutton));

  main_hpaned = gtk_hpaned_new ();
  gtk_widget_show (main_hpaned);
  gtk_box_pack_start (GTK_BOX (vbox1), main_hpaned, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (main_hpaned), 0);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_paned_pack1 (GTK_PANED (main_hpaned), viewport1, TRUE, FALSE);

  main_drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (main_drawingarea);
  gtk_container_add (GTK_CONTAINER (viewport1), main_drawingarea);
  gtk_widget_set_size_request (main_drawingarea, 512, 384);

  properties_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (properties_scrolledwindow);
  gtk_paned_pack2 (GTK_PANED (main_hpaned), properties_scrolledwindow, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (properties_scrolledwindow), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  properties_viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (properties_viewport);
  gtk_container_add (GTK_CONTAINER (properties_scrolledwindow), properties_viewport);
  gtk_widget_set_size_request (properties_viewport, 119, 88);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (properties_viewport), GTK_SHADOW_NONE);

  properties_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (properties_vbox);
  gtk_container_add (GTK_CONTAINER (properties_viewport), properties_vbox);
  gtk_widget_set_size_request (properties_vbox, 1, -1);

  label6 = gtk_label_new (_("Ten widget jest\nniewidoczny.\nZawierajacy go vbox\nsluzy do umieszczania\nzestawow edycyjnych.\n"));
  gtk_box_pack_start (GTK_BOX (properties_vbox), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_CENTER);

  status_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (status_hbox);
  gtk_box_pack_start (GTK_BOX (vbox1), status_hbox, FALSE, TRUE, 0);
  gtk_widget_set_size_request (status_hbox, 66, 20);

  n0_statusbar = gtk_statusbar_new ();
  gtk_widget_show (n0_statusbar);
  gtk_box_pack_start (GTK_BOX (status_hbox), n0_statusbar, FALSE, FALSE, 0);
  gtk_widget_set_size_request (n0_statusbar, 90, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (n0_statusbar), FALSE);

  n1_statusbar = gtk_statusbar_new ();
  gtk_widget_show (n1_statusbar);
  gtk_box_pack_start (GTK_BOX (status_hbox), n1_statusbar, FALSE, FALSE, 0);
  gtk_widget_set_size_request (n1_statusbar, 90, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (n1_statusbar), FALSE);

  n2_statusbar = gtk_statusbar_new ();
  gtk_widget_show (n2_statusbar);
  gtk_box_pack_start (GTK_BOX (status_hbox), n2_statusbar, FALSE, FALSE, 0);
  gtk_widget_set_size_request (n2_statusbar, 90, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (n2_statusbar), FALSE);

  n3_statusbar = gtk_statusbar_new ();
  gtk_widget_show (n3_statusbar);
  gtk_box_pack_start (GTK_BOX (status_hbox), n3_statusbar, FALSE, FALSE, 0);
  gtk_widget_set_size_request (n3_statusbar, 90, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (n3_statusbar), FALSE);

  n4_statusbar = gtk_statusbar_new ();
  gtk_widget_show (n4_statusbar);
  gtk_box_pack_start (GTK_BOX (status_hbox), n4_statusbar, FALSE, FALSE, 0);
  gtk_widget_set_size_request (n4_statusbar, 90, -1);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (n4_statusbar), FALSE);

  n5_statusbar = gtk_statusbar_new ();
  gtk_widget_show (n5_statusbar);
  gtk_box_pack_start (GTK_BOX (status_hbox), n5_statusbar, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) main_window, "key_press_event",
                    G_CALLBACK (on_main_window_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (on_main_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) main_window, "destroy_event",
                    G_CALLBACK (on_main_window_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) new_menuitem, "activate",
                    G_CALLBACK (on_new_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) open_menuitem, "activate",
                    G_CALLBACK (on_open_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) save_menuitem, "activate",
                    G_CALLBACK (on_save_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as, "activate",
                    G_CALLBACK (on_save_as_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) export_menuitem, "activate",
                    G_CALLBACK (on_export_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) quit_menuitem, "activate",
                    G_CALLBACK (on_quit_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) cut_menuitem, "activate",
                    G_CALLBACK (on_cut_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) copy_menuitem, "activate",
                    G_CALLBACK (on_copy_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) paste_menuitem, "activate",
                    G_CALLBACK (on_paste_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) delete_menuitem, "activate",
                    G_CALLBACK (on_delete_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) about_menuitem, "activate",
                    G_CALLBACK (on_about_mi_activate),
                    NULL);
  g_signal_connect ((gpointer) new_toolbutton, "clicked",
                    G_CALLBACK (on_new_toolbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) open_toolbutton, "clicked",
                    G_CALLBACK (on_open_toolbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) save_toolbutton, "clicked",
                    G_CALLBACK (on_save_toolbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) undo_toolbutton, "clicked",
                    G_CALLBACK (on_undo_toolbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) record_toolbutton, "clicked",
                    G_CALLBACK (on_record_toolbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit_toolbutton, "clicked",
                    G_CALLBACK (on_quit_toolbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) select_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_select_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) move_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_move_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) signals_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_signals_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) rotate_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_rotate_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createPoints_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createPoints_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createPointFeatures_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createPointFeatures_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createLines_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createLines_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) connectPoints_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_connectPoints_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createRailLines_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createRailLines_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createMiscLines_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createMiscLines_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createTracks_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createTracks_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) import_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_import_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) createFence_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_createFence_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) catenary_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_catenary_mode_radiotoolbutton_toggled),
                    NULL);
  g_signal_connect ((gpointer) fill_mode_radiotoolbutton, "toggled",
                    G_CALLBACK (on_fill_mode_radiotoolbutton_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, main_menubar, "main_menubar");
  GLADE_HOOKUP_OBJECT (main_window, file_menuitem, "file_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, file_menuitem_menu, "file_menuitem_menu");
  GLADE_HOOKUP_OBJECT (main_window, new_menuitem, "new_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, open_menuitem, "open_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, save_menuitem, "save_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, save_as, "save_as");
  GLADE_HOOKUP_OBJECT (main_window, separator1_menuitem, "separator1_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, export_menuitem, "export_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (main_window, quit_menuitem, "quit_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, edit_menuitem, "edit_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, edit_menuitem_menu, "edit_menuitem_menu");
  GLADE_HOOKUP_OBJECT (main_window, cut_menuitem, "cut_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, copy_menuitem, "copy_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, paste_menuitem, "paste_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, delete_menuitem, "delete_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, view_menuitem, "view_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, help_menuitem, "help_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, help_menuitem_menu, "help_menuitem_menu");
  GLADE_HOOKUP_OBJECT (main_window, about_menuitem, "about_menuitem");
  GLADE_HOOKUP_OBJECT (main_window, main_toolbar, "main_toolbar");
  GLADE_HOOKUP_OBJECT (main_window, new_toolbutton, "new_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, open_toolbutton, "open_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, save_toolbutton, "save_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, n1_separatortoolitem, "n1_separatortoolitem");
  GLADE_HOOKUP_OBJECT (main_window, undo_toolbutton, "undo_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, record_toolbutton, "record_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem3, "separatortoolitem3");
  GLADE_HOOKUP_OBJECT (main_window, settings_toolbutton, "settings_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, quit_toolbutton, "quit_toolbutton");
  GLADE_HOOKUP_OBJECT (main_window, n3_separatortoolitem, "n3_separatortoolitem");
  GLADE_HOOKUP_OBJECT (main_window, select_mode_radiotoolbutton, "select_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, move_mode_radiotoolbutton, "move_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, signals_mode_radiotoolbutton, "signals_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, rotate_mode_radiotoolbutton, "rotate_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createPoints_mode_radiotoolbutton, "createPoints_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createPointFeatures_mode_radiotoolbutton, "createPointFeatures_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createLines_mode_radiotoolbutton, "createLines_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, connectPoints_mode_radiotoolbutton, "connectPoints_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createRailLines_mode_radiotoolbutton, "createRailLines_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createMiscLines_mode_radiotoolbutton, "createMiscLines_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createTracks_mode_radiotoolbutton, "createTracks_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, import_mode_radiotoolbutton, "import_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, createFence_mode_radiotoolbutton, "createFence_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, catenary_mode_radiotoolbutton, "catenary_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, fill_mode_radiotoolbutton, "fill_mode_radiotoolbutton");
  GLADE_HOOKUP_OBJECT (main_window, main_hpaned, "main_hpaned");
  GLADE_HOOKUP_OBJECT (main_window, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (main_window, main_drawingarea, "main_drawingarea");
  GLADE_HOOKUP_OBJECT (main_window, properties_scrolledwindow, "properties_scrolledwindow");
  GLADE_HOOKUP_OBJECT (main_window, properties_viewport, "properties_viewport");
  GLADE_HOOKUP_OBJECT (main_window, properties_vbox, "properties_vbox");
  GLADE_HOOKUP_OBJECT (main_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (main_window, status_hbox, "status_hbox");
  GLADE_HOOKUP_OBJECT (main_window, n0_statusbar, "n0_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, n1_statusbar, "n1_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, n2_statusbar, "n2_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, n3_statusbar, "n3_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, n4_statusbar, "n4_statusbar");
  GLADE_HOOKUP_OBJECT (main_window, n5_statusbar, "n5_statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *drawingarea2;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("Editor - 3D view"));

  drawingarea2 = gtk_drawing_area_new ();
  gtk_container_add (GTK_CONTAINER (window2), drawingarea2);

  g_signal_connect ((gpointer) window2, "delete_event",
                    G_CALLBACK (on_window2_delete_event),
                    NULL);
  g_signal_connect ((gpointer) window2, "destroy_event",
                    G_CALLBACK (on_window2_destroy_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, drawingarea2, "drawingarea2");

  return window2;
}

GtkWidget*
create_ghost_window (void)
{
  GtkWidget *ghost_window;
  GtkWidget *drawingarea;

  ghost_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ghost_window), _("Ghost"));

  drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea);
  gtk_container_add (GTK_CONTAINER (ghost_window), drawingarea);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ghost_window, ghost_window, "ghost_window");
  GLADE_HOOKUP_OBJECT (ghost_window, drawingarea, "drawingarea");

  return ghost_window;
}

GtkWidget*
create_warning_window (void)
{
  GtkWidget *warning_window;
  GtkWidget *vbox;
  GtkWidget *viewport;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label;
  GtkWidget *hbox;
  GtkWidget *ok_button;

  warning_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (warning_window), _("Editor - warning"));
  gtk_window_set_position (GTK_WINDOW (warning_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_resizable (GTK_WINDOW (warning_window), FALSE);

  vbox = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (warning_window), vbox);
  gtk_container_set_border_width (GTK_CONTAINER (vbox), 6);

  viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport);
  gtk_box_pack_start (GTK_BOX (vbox), viewport, TRUE, TRUE, 0);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport), GTK_SHADOW_NONE);

  hbox10 = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (viewport), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label = gtk_label_new (_("??????\n????????????????????\n????"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox10), label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label), GTK_JUSTIFY_CENTER);

  hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox);
  gtk_box_pack_start (GTK_BOX (vbox), hbox, FALSE, FALSE, 0);

  ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_button);
  gtk_box_pack_start (GTK_BOX (hbox), ok_button, TRUE, FALSE, 0);
  gtk_widget_set_size_request (ok_button, 60, -1);

  g_signal_connect ((gpointer) warning_window, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) warning_window, "destroy_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect_swapped ((gpointer) ok_button, "released",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (warning_window));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (warning_window, warning_window, "warning_window");
  GLADE_HOOKUP_OBJECT (warning_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (warning_window, viewport, "viewport");
  GLADE_HOOKUP_OBJECT (warning_window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (warning_window, image10, "image10");
  GLADE_HOOKUP_OBJECT (warning_window, label, "label");
  GLADE_HOOKUP_OBJECT (warning_window, hbox, "hbox");
  GLADE_HOOKUP_OBJECT (warning_window, ok_button, "ok_button");

  return warning_window;
}

GtkWidget*
create_error_window (void)
{
  GtkWidget *error_window;
  GtkWidget *vbox;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label;
  GtkWidget *hbox;
  GtkWidget *button;

  error_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (error_window), _("Editor - error"));
  gtk_window_set_resizable (GTK_WINDOW (error_window), FALSE);

  vbox = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (error_window), vbox);
  gtk_container_set_border_width (GTK_CONTAINER (vbox), 6);

  hbox11 = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox), hbox11, FALSE, FALSE, 0);

  image11 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label = gtk_label_new (_("???????????????????????????\n????????????????????\n"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox11), label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label), GTK_JUSTIFY_CENTER);

  hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox);
  gtk_box_pack_start (GTK_BOX (vbox), hbox, FALSE, FALSE, 0);

  button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button);
  gtk_box_pack_start (GTK_BOX (hbox), button, TRUE, FALSE, 0);
  gtk_widget_set_size_request (button, 60, -1);

  g_signal_connect ((gpointer) error_window, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) error_window, "destroy_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button, "released",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error_window, error_window, "error_window");
  GLADE_HOOKUP_OBJECT (error_window, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (error_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (error_window, image11, "image11");
  GLADE_HOOKUP_OBJECT (error_window, label, "label");
  GLADE_HOOKUP_OBJECT (error_window, hbox, "hbox");
  GLADE_HOOKUP_OBJECT (error_window, button, "button");

  return error_window;
}

GtkWidget*
create_quit_dialog (void)
{
  GtkWidget *quit_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *dialog_action_area1;
  GtkWidget *yes_button;
  GtkWidget *alignment4;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *no_button;
  GtkWidget *alignment2;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *cancel_button;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;

  quit_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (quit_dialog), _("Editor - quit / save"));
  gtk_window_set_modal (GTK_WINDOW (quit_dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (quit_dialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (quit_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (quit_dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  hbox1 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), hbox1, FALSE, FALSE, 0);

  image1 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Save scenery before quit?"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label1), 4, 4);

  dialog_action_area1 = GTK_DIALOG (quit_dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  yes_button = gtk_button_new ();
  gtk_widget_show (yes_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (quit_dialog), yes_button, GTK_RESPONSE_YES);
  GTK_WIDGET_SET_FLAGS (yes_button, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (yes_button), alignment4);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic ("Yes");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  no_button = gtk_button_new ();
  gtk_widget_show (no_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (quit_dialog), no_button, GTK_RESPONSE_NO);
  GTK_WIDGET_SET_FLAGS (no_button, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (no_button), alignment2);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic ("No");
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  cancel_button = gtk_button_new ();
  gtk_widget_show (cancel_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (quit_dialog), cancel_button, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (cancel_button), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic ("Cancel");
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) quit_dialog, "response",
                    G_CALLBACK (on_quit_dialog_response),
                    NULL);
  g_signal_connect ((gpointer) quit_dialog, "delete_event",
                    G_CALLBACK (gtk_true),
                    NULL);
  g_signal_connect ((gpointer) quit_dialog, "destroy_event",
                    G_CALLBACK (gtk_true),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (quit_dialog, quit_dialog, "quit_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (quit_dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (quit_dialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (quit_dialog, image1, "image1");
  GLADE_HOOKUP_OBJECT (quit_dialog, label1, "label1");
  GLADE_HOOKUP_OBJECT_NO_REF (quit_dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (quit_dialog, yes_button, "yes_button");
  GLADE_HOOKUP_OBJECT (quit_dialog, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (quit_dialog, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (quit_dialog, image5, "image5");
  GLADE_HOOKUP_OBJECT (quit_dialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (quit_dialog, no_button, "no_button");
  GLADE_HOOKUP_OBJECT (quit_dialog, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (quit_dialog, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (quit_dialog, image3, "image3");
  GLADE_HOOKUP_OBJECT (quit_dialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (quit_dialog, cancel_button, "cancel_button");
  GLADE_HOOKUP_OBJECT (quit_dialog, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (quit_dialog, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (quit_dialog, image4, "image4");
  GLADE_HOOKUP_OBJECT (quit_dialog, label4, "label4");

  return quit_dialog;
}

GtkWidget*
create_new_dialog (void)
{
  GtkWidget *new_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label10;
  GtkWidget *dialog_action_area2;
  GtkWidget *yes_new_button;
  GtkWidget *alignment5;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label7;
  GtkWidget *no_new_button;
  GtkWidget *alignment6;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label8;
  GtkWidget *cancel_new_button;
  GtkWidget *alignment7;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label9;

  new_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (new_dialog), _("Editor - new / save"));
  gtk_window_set_modal (GTK_WINDOW (new_dialog), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (new_dialog), FALSE);
  gtk_window_set_type_hint (GTK_WINDOW (new_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (new_dialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  hbox9 = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), hbox9, FALSE, FALSE, 0);

  image9 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label10 = gtk_label_new (_("Save scenery before creating new one?"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox9), label10, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (new_dialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  yes_new_button = gtk_button_new ();
  gtk_widget_show (yes_new_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (new_dialog), yes_new_button, GTK_RESPONSE_YES);
  GTK_WIDGET_SET_FLAGS (yes_new_button, GTK_CAN_DEFAULT);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (yes_new_button), alignment5);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Yes"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  no_new_button = gtk_button_new ();
  gtk_widget_show (no_new_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (new_dialog), no_new_button, GTK_RESPONSE_NO);
  GTK_WIDGET_SET_FLAGS (no_new_button, GTK_CAN_DEFAULT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (no_new_button), alignment6);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("No"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox7), label8, FALSE, FALSE, 0);

  cancel_new_button = gtk_button_new ();
  gtk_widget_show (cancel_new_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (new_dialog), cancel_new_button, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_new_button, GTK_CAN_DEFAULT);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (cancel_new_button), alignment7);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox8), label9, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) new_dialog, "response",
                    G_CALLBACK (on_new_dialog_response),
                    NULL);
  g_signal_connect ((gpointer) new_dialog, "delete_event",
                    G_CALLBACK (gtk_true),
                    NULL);
  g_signal_connect ((gpointer) new_dialog, "destroy_event",
                    G_CALLBACK (gtk_true),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (new_dialog, new_dialog, "new_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (new_dialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (new_dialog, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (new_dialog, image9, "image9");
  GLADE_HOOKUP_OBJECT (new_dialog, label10, "label10");
  GLADE_HOOKUP_OBJECT_NO_REF (new_dialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (new_dialog, yes_new_button, "yes_new_button");
  GLADE_HOOKUP_OBJECT (new_dialog, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (new_dialog, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (new_dialog, image6, "image6");
  GLADE_HOOKUP_OBJECT (new_dialog, label7, "label7");
  GLADE_HOOKUP_OBJECT (new_dialog, no_new_button, "no_new_button");
  GLADE_HOOKUP_OBJECT (new_dialog, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (new_dialog, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (new_dialog, image7, "image7");
  GLADE_HOOKUP_OBJECT (new_dialog, label8, "label8");
  GLADE_HOOKUP_OBJECT (new_dialog, cancel_new_button, "cancel_new_button");
  GLADE_HOOKUP_OBJECT (new_dialog, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (new_dialog, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (new_dialog, image8, "image8");
  GLADE_HOOKUP_OBJECT (new_dialog, label9, "label9");

  return new_dialog;
}

